name: Azurite (local) functional tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  azurite-tests-linux:
    name: Azurite tests (Linux)
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-linux'
      GEN: ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;'
      AZURE_STORAGE_ACCOUNT: devstoreaccount1
      HTTP_PROXY_RUNNING: '1'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'

    - uses: actions/setup-node@v4

    - name: install Azure test service
      run: |
        sudo apt-get install -y azure-cli squid ninja-build
        npm install -g azurite

    - name: Launch & populate Azure test service
      run: |
        azurite > azurite_log.txt 2>&1 &
        sudo ./scripts/run_squid.sh --port 3128 --log_dir squid_logs &
        sudo ./scripts/run_squid.sh --port 3129 --log_dir squid_auth_logs --auth &
        sleep 10
        ./scripts/upload_test_files_to_azurite.sh

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

    # Build extension
    - name: Build extension
      env:
        GEN: ninja
      run: |
        make release

    - name: Test extension
      run: |
        make test

    - name: Run test data integrity check
      run: |
        ./build/release/duckdb -c "CREATE PERSISTENT SECRET s1 (TYPE AZURE, CONNECTION_STRING '$AZURE_STORAGE_CONNECTION_STRING')"
        DUCKDB_AZURE_PERSISTENT_SECRET_AVAILABLE=1 ./build/release/test/unittest "*test/sql/test_data_integrity.test"

    - name: Azure test server log
      if: always()
      shell: bash
      run: |
        echo "## azurite"
        cat azurite_log.txt

        echo "## squid"
        sudo cat squid_logs/*

        echo "## squid auth"
        sudo cat squid_auth_logs/*

  azurite-tests-macos:
    name: Azurite tests (MacOS)
    runs-on: macos-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-osx'
      OSX_BUILD_ARCH: 'x86_64'
      GEN: ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;'
      AZURE_STORAGE_ACCOUNT: devstoreaccount1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Ninja
        run: brew install ninja

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb_azure' }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Build extension
        shell: bash
        run: |
          make release

      - uses: actions/setup-node@v3
      - name: Launch & populate Azure test service
        run: |
          npm install -g azurite
          azurite > azurite_log.txt 2>&1 &
          sleep 10
          ./scripts/upload_test_files_to_azurite.sh

      - name: Test Extension
        shell: bash
        run: |
          make test

      - name: Run test data integrity check
        run: |
          ./build/release/duckdb -c "CREATE PERSISTENT SECRET s1 (TYPE AZURE, CONNECTION_STRING '$AZURE_STORAGE_CONNECTION_STRING')"
          DUCKDB_AZURE_PERSISTENT_SECRET_AVAILABLE=1 ./build/release/test/unittest "*test/sql/test_data_integrity.test"

      - name: Azure test server log
        if: always()
        shell: bash
        run: |
          echo "## azurite"
          cat azurite_log.txt

  azurite-tests-windows:
    name: Azurite tests (Windows)
    runs-on: windows-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-windows'
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
      AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;'
      AZURE_STORAGE_ACCOUNT: devstoreaccount1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Build extension
        run: |
          make release

      - uses: actions/setup-node@v3
      - name: Launch & populate Azure test service
        run: |
          npm install -g azurite
          azurite > azurite_log.txt 2>&1 &
          sleep 10
          ./scripts/upload_test_files_to_azurite.sh

      - name: Test Extension
        shell: bash
        run: |
          build/release/test/Release/unittest.exe --test-dir . "[sql]"

      - name: Run test data integrity check
        run: |
          ls build
          ls build/release
          ./build/release/Release/duckdb.exe -c "CREATE PERSISTENT SECRET s1 (TYPE AZURE, CONNECTION_STRING '$AZURE_STORAGE_CONNECTION_STRING')"
          DUCKDB_AZURE_PERSISTENT_SECRET_AVAILABLE=1 build/release/test/Release/unittest.exe "*test/sql/test_data_integrity.test"

      - name: Azure test server log
        if: always()
        shell: bash
        run: |
          cat azurite_log.txt
